requirements:
  unknown: "&cNot Allowed"
  property_requirement: "&r&cRequires: &6$property &cof &4$value"
  property_max: "&r&cYour &6$property &cis maxed out"
  property_max_inclusive: "&r&cYour &6$property &cis maxed out"
  property_min: "&r&cYour &6$property &cmust be greater than &4$value"
  property_min_inclusive: "&r&cYour &6$property &cmust be at least &4$value"
  no_resource_pack: "&cYou must have the resource pack"
  no_wand: "&cYou must be holding a wand!"
  no_template: "&cYou may not do that with $wand&c."
  no_modifier: "&cYou must have &6$modifier &cto do that."
  no_region: "&cYou may not do that here."
  no_world: "&You may not do that here."
  no_path: "&cYou may not learn here."
  no_class: "&cYou must be a $class"
  no_required_path: "&cYou must be at least $path&r!"
  no_path_exact: "&cYou must be at $path&r!"
  no_path_end: "&cYou must be ready to advance from $path&r!"
  no_weather: "&cThe weather is not right for that"
  no_client_platform: "You're not on the right platform for that"
  light: "Light Level"
  time: "Time of Day"
  moon: "Phase of Moon"
  height: "Height"
  server_version: "Server Version"
  currency: "$currency"
  item: "$item"
  no_cast: "&cYou must cast $spell first"
  no_spell_inventory: "&cYou must have your spell inventory open"
  no_indoors: "May only be used indoors"
  indoors: "Must not be indoors"
  no_stay: "Must be set to stay"
  no_owned: "Must have an owner"
  stay: "Must not be set to stay"
  owned: "Must not have an owner"
